services:
  vpn:
    image: qmcgaw/gluetun:v3.41.1
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env.vpn
    networks:
      - zone-debrid
  zone-debrid-backend:
    build: ../backend
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    networks:
      - web
      - zone-debrid
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - 27017:27017
    command:
      - --auth
    env_file:
      - db.env 
    volumes:
      - ../data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - zone-debrid

networks:
  zone-debrid:
  web:
    name: pangolin
    external: true