name: rsync and deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}

      - name: Sync project to server
        run: |
          rsync -avz ./apps/backend ${{ secrets.REMOTE_HOST }}:./zone-debrid/
          rsync -avz ./deploy ${{ secrets.REMOTE_HOST }}:./zone-debrid/
        shell: bash

      - name: Build and restart Docker app on remote host
        run: |
          ssh ${{ secrets.REMOTE_HOST }} '
            cd ./zone-debrid/deploy &&
            docker compose up -d --build
          '
        shell: bash